### ISSUE TITLE
platform: jade() not working with workspaces

### ISSUE THREAD

**Issue by Addy90** [aricci303/cartago#1]
I tried to use platform: jade() with workspaces and artifacts in two different projects with both 0.6-SNAPSHOT from sourceforge as from GitHub (self packaged via gradle) - did not work, the workspace was not joined. When I didn't use JADE as underlying base, it is working immediatly. Try on the coordination_env tutorial for example!

Is there anything one can do? It would be good to combine JaCaMo with third party agents in JADE when using Artifacts.

Thank you :)

**Comment by jomifred** [comment]
Hi Adrian, I've committed some changes in the JaCaMo github repository to fix that issues.

**Comment by Addy90** [comment]
Hi Jomi,
it seems to work now with jade() platform in combination with artifacts and workspaces! Very cool, thank you a lot!

**Comment by jomifred** [comment]
We introduced a lot of changes in the current development version of jacamo related tools and we still do not fix (or discover) some bugs. So thanks for reporting them!
